import torch
from torch import nn
import torch.nn.functional as F
import numpy as np

from src.utils import visualize_perturbations

device = "cuda" if torch.cuda.is_available() else "cpu"


class OnePixelAttack:
    """
    This class implements the black-box adversarial attack One Pixel Attack (OPA).
    """

    def __init__(
        self, model: nn.Module, img: torch.Tensor, label: int, n: int = 100
    ) -> None:
        """
        Constructor of the class.

        Parameters
        ----------
        model : Model used.
        img   : Original image. Dimensions: [channels, height, width].
        label : Real label for the image.
        n     : Size of the population.
        """

        # Class attributes
        self.n = n
        self.F = 0.5
        self.img = img
        self.perturbed_img = img.clone()
        self.label = label
        self.model = model

        # Create and evaluate population
        self.population = torch.rand(n, 5)
        self.fitness = self._evaluate_population()
        with torch.no_grad():
            prob = self.model(img.unsqueeze(0)).squeeze()
        self.historical_fitness = [F.softmax(prob, dim=0)[self.label].item()]

    @staticmethod
    def _add_perturbation(
        perturbations: list[torch.Tensor], img: torch.Tensor
    ) -> torch.Tensor:
        """
        Adds a finite number of perturbations (specifically len(perturbations)).

        Parameters
        ----------
        perturbations : Perturbations to made. Dimensions of each perturbation: [5].
        img           : Image to which perturbations are applied. Dimensions: [channels,
                        height, width].

        Returns
        -------
        p_img : Perturbed image. Dimensions: [channels, height, width].
        """

        perturbated_img: torch.Tensor = img.clone()

        for perturbation in perturbations:
            h_rel: float = abs(perturbation[0].item())

            if h_rel == 1:
                h_rel -= 1

            w_rel: float = abs(perturbation[1].item())

            if w_rel == 1:
                w_rel -= 1

            h: int = int(h_rel * img.shape[1])
            w: int = int(w_rel * img.shape[2])

            perturbated_img[0, h, w] = perturbation[2]
            perturbated_img[1, h, w] = perturbation[3]
            perturbated_img[2, h, w] = perturbation[4]

        return perturbated_img.clip(0, 1)

    def _fitness_function(self, perturbed_img: torch.Tensor) -> float:
        """
        Calculates the fitness of the perturbed image generated by an individual.

        Parameters
        ----------
        perturbed_img : Perturbed image generated by an individual. Dimensions:
                        [channels, height, width].

        Returns
        -------
        Probability asigned by the model to the real class.
        """

        with torch.no_grad():
            prob = self.model(perturbed_img.unsqueeze(0)).squeeze()

        return F.softmax(prob, dim=0)[self.label].item()

    def _evaluate_population(self) -> torch.Tensor:
        """
        Evaluates the fitness of the entire population.

        Returns
        -------
        fitness : Fitness of the entire population. Dimensions: [self.n, 1].
        """

        fitness: torch.Tensor = torch.zeros((self.n, 1))

        for i in range(self.n):
            perturbation: list[torch.Tensor] = [self.population[i]]

            perturbated_img: torch.Tensor = self._add_perturbation(
                perturbation, self.img
            )

            fitness[i] = self._fitness_function(perturbated_img)

        return fitness

    def _generate_new_population(self) -> None:
        """
        Updates the population based on the algorithm x_i = x_r1 + F * (x_r2 - x_r3)
        and selects the best between each child and parent.
        """

        new_population: torch.Tensor = torch.zeros_like(self.population)

        for i in range(self.n):
            r_expanded: torch.Tensor = torch.randperm(self.n)[:4]

            if (r_expanded == i).any():
                r:torch.Tensor = r_expanded[i != r_expanded]

            else:
                r:torch.Tensor = r_expanded[0:3]
    
            r1: int = r[0]
            r2: int = r[1]
            r3: int = r[2]

            v_i = self.population[r1] + self.F * (
                self.population[r2] - self.population[r3]
            )
            v_i_clipped: torch.Tensor = v_i.clip(0, 1).to(device)

            perturbated_img: torch.Tensor = self._add_perturbation(
                [v_i_clipped], self.img
            )

            if self.fitness[i].item() > self._fitness_function(perturbated_img):
                new_population[i] = v_i_clipped

            else:
                new_population[i] = self.population[i]

        self.population = new_population
        self.fitness = self._evaluate_population()

    def _get_perturbations(
        self, epochs: int, d: int, print_every: int | None
    ) -> list[torch.Tensor]:
        """
        Obtains the perturbations using differential evolution.

        Parameters
        ----------
        epochs      : Number of epochs we train.
        d           : Number of pixels we change.
        print_every : Number of epochs we print the training phase.

        Returns
        -------
        perturbations : Best perturbations found. Dimensions of each perturbation: [5].
        """

        for epoch in range(epochs):

            self._generate_new_population()

            if (self.fitness <= 0.05).count_nonzero() >= d:
                break

            if epoch % print_every == 0:
                print("=" * 20)
                print("Fitness of perturbations")
                print(self.fitness)

        ordered_perturbations: list[torch.Tensor] = []

        fitness_ordered: torch.Tensor
        _, fitness_ordered = self.fitness.squeeze().sort()
        ordered_idxs = fitness_ordered[:d]

        for idx in ordered_idxs:
            ordered_perturbations.append(self.population[idx.item()])

        return ordered_perturbations

    def perturb_img(
        self,
        epochs: int = 50,
        d: int = 1,
        print_every: int | None = None,
        show: bool = True,
        **kwargs_visualize
    ) -> tuple[torch.Tensor, list[torch.Tensor]]:
        """
        Perturbs an image.

        Parameters
        ----------
        epochs      : Number of epochs we train.
        d           : Number of pixels we change.
        print_every : Number of epochs we print the training phase.
        show        : Boolean parameter that decides whether to save the
                      figure or not.
        title       : Title of the image in case it is saved.

        Returns
        -------
        perturbed_img : Perturbed image. Dimensions: [channels, height,
                        width].
        perturbations : Perturbations made. Dimensions of each perturbation:
                        [channels, height, width].
        """

        perturbations: list[torch.Tensor] = self._get_perturbations(
            epochs, d, print_every
        )

        perturbated_img: torch.Tensor = self._add_perturbation(
            perturbations, self.img
        )

        if show:
            visualize_perturbations(
                perturbated_img.detach(),
                self.img.detach(),
                self.label,
                self.model,
                **kwargs_visualize
            )

        return perturbated_img, perturbations